package orange.wz.provider.tools;

public enum WzType {
    FOLDER,
    WZ_FILE,
    DIRECTORY,
    IMAGE,
    CANVAS_PROPERTY,
    CONVEX_PROPERTY,
    DOUBLE_PROPERTY,
    FLOAT_PROPERTY,
    INT_PROPERTY,
    LIST_PROPERTY,
    LONG_PROPERTY,
    NULL_PROPERTY,
    PNG_PROPERTY,
    RAW_DATA_PROPERTY,
    SHORT_PROPERTY,
    SOUND_PROPERTY,
    STRING_PROPERTY,
    UOL_PROPERTY,
    VECTOR_PROPERTY,
}
